### ISSUE TITLE
Prevent conflicts with terminal mappings (like `jk` to enter normal mode)

### ISSUE THREAD

**Issue by Lxtharia** [SR-MyStar/yazi.nvim#2]
Hello, nice plugin!
One issue I have is that i mapped `jk` to exit terminal mode. So when i move down and up it will enter normal mode and my cursor moves freely around. it also waits for [timeoutlen](https://neovim.io/doc/user/options.html#'timeoutlen') milliseconds before it actually triggers j.
Is there a way to clear or override these mapping when in Yazi?
Thanks!

**Comment by Buer-Nahida** [comment]
`command_args.on_open` option can implement it
```lua
opts = {
  command_args = {
    on_open = function()
      vim.keymap.del("t", "jk", { buffer = true, nowait = true })
    end,
  }
}
```

**Comment by Lxtharia** [comment]
Thank you!
