### ISSUE TITLE
Feature request: Mousewheeel support

### ISSUE THREAD

**Issue by Zeioth** [SR-MyStar/yazi.nvim#3]
Back in the day I implemented this in rnvimr and implementing the same feature here would be trivial.

* The only thing necessary for this to work is disabling mouse support while on the yazi.nvim window.
* And re-enabing it when leaving the window.

You can check my PR as reference:
https://github.com/kevinhwang91/rnvimr/issues/58#issuecomment-1550090411

**Comment by Buer-Nahida** [comment]
I give up this project, because I haven't extra time to care it and I found a plugin \([mikavilpas/yazi.nvim](https://github.com/mikavilpas/yazi.nvim)\) same as and better than this plugin, you can use that plugin instead of this.
